### ISSUE TITLE
Unable to use the app

### ISSUE THREAD

**Issue by jyotivsharma** [JCCKwong/PUVOP#5]
Every time I try using the PUVOP app I get the following response

"Oh no.
Error running app. If this keeps happening, please [contact support](https://github.com/jcckwong/puvop/issues/new).

request for your help

**Comment by JCCKwong** [comment]
Thank you for your comment. The latest release (v.1.2.0) should be up and running now. Thanks again for your patience and interest in our PUVOP app.
